### ISSUE TITLE
Add a DESCRIPTION file for better dependency management and documentation

### ISSUE THREAD

**Issue by Thomas-K-John** [Mindshift-Analytics/roicalculator#10]
The project currently does not have a `DESCRIPTION` file, which is essential for providing metadata, managing package dependencies, and facilitating package development.

**Comment by sanjmeh** [comment]
thanks for opening an issue.

**Comment by vaish1794** [comment]
Assigning it to myself.

**Comment by AparnaPentakota** [comment]
"Hi, I would like to work on this issue. Please assign it to me."

**Comment by sanjmeh** [comment]
this is already done. Please pick another issue.

**Comment by AparnaPentakota** [comment]
okey sir
