### ISSUE TITLE
Handle empty value in "Number of HEMM", "Number of diesel bowsers/site" and "HEMM Fuel Consumption/Day"

### ISSUE THREAD

**Issue by Thomas-K-John** [Mindshift-Analytics/roicalculator#16]
In the top section of the app, we have a input box to collect "Number of HEMM", "Number of diesel bowsers/site" and "HEMM Fuel Consumption/Day". When the user removes the value from the input box, we see a few error messages in the UI.
This issue is similar to #6 

![Errors](https://github.com/user-attachments/assets/d549c010-8088-4c0b-ac20-ee572b8a080a)

**Comment by sanjmeh** [comment]
there are many places that show the error of empty selection. One more is this.
![Screenshot 2024-12-04 at 6 23 52 PM](https://github.com/user-attachments/assets/020c68cb-b387-463f-ae4a-739fc04f4aa4)

**Comment by SwarnimShekhar** [comment]
Hello, I would like to work on this issue. Please assign it to me.

**Comment by sanjmeh** [comment]
Sure. 
Please ensure you have read the README and follow instructions for raising PR.
