### ISSUE TITLE
Remove spelling mistakes and fix grammatical errors

### ISSUE THREAD

**Issue by bkowshik** [Mindshift-Analytics/roicalculator#2]
## Example

At the following line of code, we need to change `acheive` to `achieve` instead.

https://github.com/Mindshift-Analytics/roicalculator/blob/e858a28451166b8ad832d5b6ee294077e05d06cd/ui.R#L144

**Comment by darshanramani** [comment]
![image](https://github.com/user-attachments/assets/90d06ec1-4fad-49d0-8b90-f0c752b25ee3)

Solved : Remove spelling mistakes and fix grammatical errors #2

**Comment by darshanramani** [comment]
Created

**Comment by AparnaPentakota** [comment]
Hi, I'd like to work on this issue Remove spelling mistakes and fix grammatical error. Could you please assign this to me?

**Comment by sanjmeh** [comment]
OK, This is just to get your github process to be tested.
After this please move to the other issue which is not taken by anybody. Already assigned to you.

**Comment by AparnaPentakota** [comment]
Solved : Remove spelling mistakes and fix grammatical errors and I send a PR #20
