### ISSUE TITLE
remove deprecated warning of gt

### ISSUE THREAD

**Issue by sanjmeh** [Mindshift-Analytics/roicalculator#23]
Remove this warning

> Warning: Since gt v0.3.0, `columns = vars(...)` has
been deprecated.
• Please use `columns = c(...)` instead.

**Comment by twinklevatwani** [comment]
Fix: Replace deprecated `vars()` with `c()` in `gt` package usage to eliminate warnings

- Updated `gt` table configurations to use `c()` for specifying columns instead of `vars()`.
- Resolved warnings caused by the deprecation of `vars()` in `gt` version 0.3.0 and later.
