### ISSUE TITLE
make the bar chart easy to understand

### ISSUE THREAD

**Issue by sanjmeh** [Mindshift-Analytics/roicalculator#25]
In the Manpower costs, the current bar chart shows the two bars overlapping (blue = original cost and orange = new cost). Since the total height of the blue bar is hidden it is not easy to understand this plot. Ideally it should be easy to see them separately. You may want to keep the bars side by side or reduce the width of the orange bar so that the blue bar full height is visible. Figure out the changes needed, and push a commit and and raise a PR with a little explanation of the code changes. Also update this issue with the new look visualisation.

![Screenshot 2024-12-04 at 9 37 11 PM](https://github.com/user-attachments/assets/f08642dc-ebf6-443b-8da3-85dd1721f9bc)

**Comment by darshanramani** [comment]
![image](https://github.com/user-attachments/assets/32950beb-6831-4fe2-8538-e9e5b1e39182)

I changed chart from on the top to side by side, hope this will solve the problem of hiding each other's value.

**Comment by darshanramani** [comment]
I created PR for #25 please review it and let me know what I can do next.

**Comment by sanjmeh** [comment]
Looks good. Will test it today.
