### ISSUE TITLE
convert side by side to stack bar

### ISSUE THREAD

**Issue by sanjmeh** [Mindshift-Analytics/roicalculator#26]
Here is a bar chart that shows savings under two heads - _sold illegally_ and _under reporting_. The user may want to know the total savings as well. Convert the current bar plot to a stacked bar plot with total as the sum of the individual components.

![Screenshot 2024-12-04 at 10 02 48 PM](https://github.com/user-attachments/assets/219bc562-d375-4279-854f-d63bcdb330df)

**Comment by darshanramani** [comment]
Please assign this to me, I'm working on it soon.
