### ISSUE TITLE
get rid of the unknown aesthetics text warning

### ISSUE THREAD

**Issue by sanjmeh** [Mindshift-Analytics/roicalculator#27]
Replication steps for this warning.
1. Go to manpower tab
2. Go to step 1 box (enter FTE details) and change the numeric value in any form

![Screenshot 2024-12-04 at 10 55 34 PM](https://github.com/user-attachments/assets/eb80d19e-65b0-4696-8a20-5dee136fee11)

4. Observe the rstudio console
> Warning in geom_bar(aes(x = Category, y = Metrics, fill = "original", text = orig_explanation),  :
  Ignoring unknown aesthetics: text
Warning in geom_bar(aes(x = Category, y = saved_value, fill = "saved", text = saved_explanation),  :
  Ignoring unknown aesthetics: text
Warning in geom_bar(aes(x = Category, y = Metrics, fill = "original", text = orig_explanation),  :
  Ignoring unknown aesthetics: text

**Comment by twinklevatwani** [comment]
Remove 'text' aesthetic from geom_bar in manpower tab to prevent warnings

**Comment by sanjmeh** [comment]
are you picking this up @twinklevatwani ?

**Comment by twinklevatwani** [comment]
Yes sir, I have done the changes and submitted the pull request

**Comment by sanjmeh** [comment]
Ok. Will check today.
