### ISSUE TITLE
Replace all occurrences of "MindShift" with "Mindshift"

### ISSUE THREAD

**Issue by bkowshik** [Mindshift-Analytics/roicalculator#3]
## Example

https://github.com/Mindshift-Analytics/roicalculator/blob/e858a28451166b8ad832d5b6ee294077e05d06cd/ui.R#L145

**Comment by dogakantarci** [comment]
Hi, I'd like to get this issue.

**Comment by sanjmeh** [comment]
Sure. Pls assign it to yourself and complete the task and send us the Pull Request. Best wishes.

**Comment by bkowshik** [comment]
Closed with https://github.com/Mindshift-Analytics/roicalculator/pull/9
