### ISSUE TITLE
Consistently style all "Info" boxes with green background instead of grey

### ISSUE THREAD

**Issue by bkowshik** [Mindshift-Analytics/roicalculator#5]
Most of the `Info` buttons have the green background like we see below:

<img width="93" alt="image" src="https://github.com/user-attachments/assets/2dbce401-0d5a-46cb-aa70-5335955bbe14">

But, there are some buttons which are grey in colour.

<img width="93" alt="image" src="https://github.com/user-attachments/assets/54c7d474-9155-4f12-bbdf-53a318769f49">

We want all "Info" buttons with white font on a green background.

**Comment by darshanramani** [comment]
Do we need to change only the background color or also icon need to keep same ?

**Comment by sanjmeh** [comment]
You may decide to do it and mention the reason. Any decision to be backed by a reason.

**Comment by bkowshik** [comment]
Closed with: https://github.com/Mindshift-Analytics/roicalculator/issues/5

**Comment by darshanramani** [comment]
![image](https://github.com/user-attachments/assets/c460f77f-0275-4291-b91c-72f53e9d87c6)

So, I made all the info buttons the same with "green background, blue border, lightbulb icon" as it gives us better UX.
