### ISSUE TITLE
Handle empty value in "Number of shifts"

### ISSUE THREAD

**Issue by bkowshik** [Mindshift-Analytics/roicalculator#6]
In the top section of the app, we have a input box to collect `Number of shifts` with a default value of `2`.

<img width="221" alt="image" src="https://github.com/user-attachments/assets/1339ca25-a97c-4e9f-9d6b-302266064620">

But, when a user removes the value of `2` from the input box, we see a few error messages in the UI.

<img width="216" alt="image" src="https://github.com/user-attachments/assets/f67ffb02-3259-4b92-9610-c437b5558378">

Make appropriate changes so these error messages don't appear for the user on the UI.

**Comment by Thomas-K-John** [comment]
I see the same issue is present for multiple other inputs and we need a general ticket to solve for all the other attributes.

**Comment by Thomas-K-John** [comment]
Thanks for the clarification. I have corrected the code and have created a new pull request. #17
